### ISSUE TITLE
关于 thunk 的两个问题

### ISSUE THREAD

**Issue by zensh** [gyson/gocsp-thunk#1]
https://github.com/tjunnone/npm-check-updates/issues/55#issuecomment-84690296

从 https://github.com/thunks/thunks 的实现来看，gocsp-thunk 的 readme 中有两个问题：
1. thunks 是惰性求值的，promise 是及早求值的，这是本质的不同，能从根本上影响代码逻辑结构；
2. thunks 是链式的，与 promise 一样；

另， Zalgo 问题是关于 API 设计的，也就是说 API 要么是同步的，要么是异步的，这是上层实现，这与 thunks 或 promise 关系不大

**Comment by gyson** [comment]
有参考 thunks，但不是按照它实现的，很多地方都不同

为了避免误解，我在 README.md 里加了 Note，把流量导向 thunks

**Comment by zensh** [comment]
在 haskell 中，thunk 就是惰性求值，把它变成及早求值是不太合适的

**Comment by gyson** [comment]
嗯，可能确实不太合适

这个 repo 主要是对 thunk API 进行各种尝试，比如 immutability, cancellation, 和 stacktrace，改的时候没考虑那么多
